<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DanteConfigEditor.Application</AssemblyName>
    <RootNamespace>DanteConfigEditor.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DanteConfigEditor.Core\DanteConfigEditor.Core.csproj" />
    <ProjectReference Include="..\DanteConfigEditor.Domain\DanteConfigEditor.Domain.csproj" />
    <ProjectReference Include="..\DanteConfigEditor.DanteXml\DanteConfigEditor.DanteXml.csproj" />
  </ItemGroup>
</Project>
